server:
  port: 8080

spring:
  application:
    name: fibonacci-microservice
    description: Spring Boot Fibonacci Microservice
  boot:
    admin:
      client:
        enabled: true
        url: http://10.5.47.129:8888/adminserver
        management-url: ${DOCKER_HOST}:${DOCKER_PORT}
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true