server:
  port: 8080

spring:
  application:
    name: fibonacci-microservice
    description: Spring Boot Fibonacci Microservice
  boot:
    admin:
      client:
        enabled: false
        url: http://localhost:8888
management:
  endpoints:
    enabled-by-default: true