server:
  port: 8080

spring:
  application:
    name: fibonacci-microservice
    description: Spring Boot Fibonacci Microservice
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8888/adminserver
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  server:
    port: 9000